<robot name="scara_cpe" xmlns:xacro="http://ros.org/wiki/xacro" >

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find scara_cpe_description)/urdf/scara_cpe.gazebo" />

       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find kobuki_description)/urdf/kobuki.urdf.xacro" />
  <xacro:include filename="$(find turtlebot_description)/urdf/stacks/hexagons.urdf.xacro"/>
  <xacro:include filename="$(find turtlebot_description)/urdf/sensors/kinect.urdf.xacro"/>

		 
  <xacro:property name="Base_LENGTH" value="0.06" />
  <xacro:property name="Link1_LENGTH" value="0.08" />
  <xacro:property name="Link2_LENGTH" value="0.047" />
  <xacro:property name="Base_HEIGHT" value="0.03" />
  <xacro:property name="Link2_HEIGHT" value="-0.025" />
  <xacro:property name="PI" value="3.14159265359" />
  <xacro:property name="PI_half" value="1.57079632679" />



  <!-- the robot -->
  <xacro:kobuki />
  <xacro:stack_hexagons parent="base_footprint" />
  <xacro:sensor_kinect parent="base_footprint" />



  <!-- LINK -->

  <link name="base_cpe">
    <visual>
      <!--<origin xyz="0.13 0.0337 0.38" rpy="-${PI_half} 0 -${PI}" />-->
	<origin xyz="0.13 0.0337 0.38" rpy="-${PI_half} 0 -${PI}" />
      <geometry>
        <mesh filename="package://scara_cpe_description/urdf/scara_cpe-base_link.dae" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0.025 0" rpy="0 0 0" />
      <mass value="0.1"/>
      <inertia
        ixx="0.0001" ixy="1e-12" ixz="1e-12"
        iyy="0.0001" iyz="1e-12"
        izz="0.0001"/>
    </inertial>    

  </link>

  <link name="link1" >

    <visual>
      <!--<origin xyz="0.13 -0.0178 0.38" rpy="-${PI_half} 0 -${PI}" />-->
	<origin xyz="0.13 -0.0178 0.38" rpy="-${PI_half} 0 -${PI}" />
      <geometry>
        <mesh filename="package://scara_cpe_description/urdf/scara_cpe-link_1.dae" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 ${Link1_LENGTH/2} 0" rpy="0 0 0" />
      <geometry>
        <box size="0.02 ${Link1_LENGTH/2} 0.05"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0.04 0" rpy="0 0 0" />
      <mass value="0.1"/>
      <inertia
        ixx="0.00003" ixy="1e-12" ixz="1e-12"
        iyy="0.00003" iyz="1e-12"
        izz="0.00003"/>
    </inertial>   

  </link>


  <link name="link2" >

    <visual>
	  <!--<origin xyz="0.15 -0.02 0.38" rpy="-${PI_half} 0 -${PI}" />-->  <!-- -1.42579632679  - pi/2 + 0.145 -->
	<origin xyz="0.135 -0.09 0.38" rpy="-${PI_half} 0 3.14159265359" />
      <geometry>
        <mesh filename="package://scara_cpe_description/urdf/scara_cpe-link_2.dae" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 ${Link2_LENGTH/2} 0" rpy="0 0 0" />
      <geometry>
        <box size="0.032 ${Link2_LENGTH} 0.06"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0.02 0" rpy="0 0 0" />
      <mass value="0.1"/>
      <inertia
        ixx="0.0001" ixy="1e-12" ixz="1e-12"
        iyy="0.0001" iyz="1e-12"
        izz="0.0001"/>
    </inertial>  

  </link>


  <link name="end_link" >
  </link>



 <!-- JOINT -->

  <joint name="base_fixed" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_cpe"/>
    <origin xyz="0 0 .035" rpy="0 0 0" />
  </joint>



  <joint name="shoulder_1_joint" type="revolute">
    <parent link="base_cpe"/>
    <child link="link1"/>
    <origin xyz="0 0.048 0" rpy="0 0 0" />
	  <limit effort="1.5" velocity="1.0" lower="-${PI_half}" upper="${PI_half}" />
	  <axis xyz="0 0 1" />
  </joint>

  <joint name="shoulder_2_joint" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0.08 0" rpy="0 0 0" /> 
	  <limit effort="1.5" velocity="1.0" lower="-2.8" upper="2.8" />
	  <axis xyz="0 0 -1" />
  </joint>


  <joint name="end_joint" type="fixed">
    <parent link="link2"/>
    <child link="end_link"/>
    <origin xyz="0 0.047 -0.025" rpy="0 0 0" />
  </joint>


  <transmission name="tran1">
    <type>SimpleTransmission</type>
    <joint name="shoulder_1_joint">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>SimpleTransmission</type>
    <joint name="shoulder_2_joint">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>  
 


</robot>
